// src/utils/pdfGenerator.js
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';
import { formatCurrency, formatDate, formatPercentage } from './formatters';

// Color constants matching brand
const COLORS = {
  primary: [45, 106, 80],
  primaryLight: [217, 236, 226],
  text: [28, 57, 45],
  textLight: [122, 132, 102],
  white: [255, 255, 255],
  expense: [249, 115, 22],
  income: [61, 131, 101],
  danger: [220, 38, 38],
  border: [232, 234, 226],
};

/**
 * Capture a DOM element as image
 */
const captureElement = async (elementId) => {
  const element = document.getElementById(elementId);
  if (!element) {
    console.warn(`Element #${elementId} not found for capture`);
    return null;
  }
  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      backgroundColor: '#ffffff',
      logging: false,
      useCORS: true,
      allowTaint: true,
    });
    return canvas.toDataURL('image/png');
  } catch (err) {
    console.error('Capture failed:', err);
    return null;
  }
};

/**
 * Add brand header to current page
 */
const addHeader = (doc, title, subtitle) => {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 35, 'F');

  doc.setFillColor(...COLORS.white);
  doc.circle(20, 17.5, 8, 'F');
  doc.setFillColor(...COLORS.primary);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('$', 17.5, 21);

  doc.setTextColor(...COLORS.white);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 35, 16);

  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, 35, 24);
  }
};

/**
 * Add footer to current page
 */
const addFooter = (doc, pageNumber, totalPages, footerText) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);

  doc.setFontSize(8);
  doc.setTextColor(...COLORS.textLight);
  doc.setFont('helvetica', 'normal');
  doc.text(footerText, 14, pageHeight - 8);
  doc.text(`${pageNumber} / ${totalPages}`, pageWidth - 14, pageHeight - 8, { align: 'right' });
};

/**
 * Add a section title
 */
const addSectionTitle = (doc, title, y) => {
  doc.setFillColor(...COLORS.primaryLight);
  doc.roundedRect(14, y - 5, 80, 8, 2, 2, 'F');
  doc.setTextColor(...COLORS.primary);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 18, y);
  return y + 8;
};

/**
 * Main PDF generation function
 */
export const generateReportPDF = async (report, options = {}) => {
  const {
    title = 'EXPENZ Financial Report',
    subtitle = 'Your Money Insights',
    footerText = 'Generated by Expenz - Smart Finance Manager',
    period = {},
    captureCharts = true,
    translations = {},
  } = options;

  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // ─── PAGE 1: COVER ─── //
  addHeader(doc, title, subtitle);

  let y = 50;

  // Generated info card
  doc.setFillColor(...COLORS.primaryLight);
  doc.roundedRect(14, y, pageWidth - 28, 20, 3, 3, 'F');
  doc.setTextColor(...COLORS.primary);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(translations.generatedOn || 'GENERATED ON', 18, y + 7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.text);
  doc.setFontSize(10);
  doc.text(
    new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }),
    18,
    y + 14
  );

  doc.setTextColor(...COLORS.primary);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(translations.period || 'PERIOD', pageWidth / 2 + 10, y + 7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.text);
  doc.setFontSize(10);
  const periodText = period.startDate
    ? `${formatDate(period.startDate)} -> ${formatDate(period.endDate)}`
    : 'All time';
  doc.text(periodText, pageWidth / 2 + 10, y + 14);

  y += 30;

  // ─── KEY METRICS TABLE ─── //
  y = addSectionTitle(doc, translations.summary || 'Financial Summary', y);
  y += 5;

  const metricsData = [
    [translations.totalIncome || 'Total Income', formatCurrency(report.summary.totalIncome)],
    [translations.totalExpenses || 'Total Expenses', formatCurrency(report.summary.totalExpense)],
    [translations.netBalance || 'Net Balance', formatCurrency(report.summary.netBalance)],
    [translations.savingsRate || 'Savings Rate', formatPercentage(report.summary.savingsRate)],
    ['Daily Avg Spending', formatCurrency(report.summary.dailyAvgExpense)],
    [translations.transactions || 'Total Transactions', String(report.summary.transactionCount)],
  ];

  // ✅ FIXED: Use autoTable(doc, options) instead of doc.autoTable(options)
  autoTable(doc, {
    startY: y,
    body: metricsData,
    theme: 'plain',
    styles: {
      font: 'helvetica',
      fontSize: 10,
      cellPadding: 4,
      lineColor: COLORS.border,
      lineWidth: 0.3,
    },
    columnStyles: {
      0: { textColor: COLORS.textLight, cellWidth: 70 },
      1: { textColor: COLORS.text, fontStyle: 'bold', halign: 'right' },
    },
    didDrawCell: (data) => {
      if (data.section === 'body') {
        doc.setDrawColor(...COLORS.border);
        doc.setLineWidth(0.2);
        doc.line(
          data.cell.x,
          data.cell.y + data.cell.height,
          data.cell.x + data.cell.width,
          data.cell.y + data.cell.height
        );
      }
    },
  });

  // ✅ FIXED: Get finalY from doc.lastAutoTable
  y = doc.lastAutoTable.finalY + 12;

  // ─── MONEY STORY ─── //
  if (report.moneyStory?.length) {
    if (y > pageHeight - 60) {
      doc.addPage();
      y = 20;
    }

    y = addSectionTitle(doc, translations.moneyStory || 'How Your Money Was Spent', y);
    y += 6;

    report.moneyStory.forEach((item) => {
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.text);
      doc.setFont('helvetica', 'normal');

      doc.setFillColor(...COLORS.primary);
      doc.circle(17, y - 0.5, 1, 'F');

      const lines = doc.splitTextToSize(item.text, pageWidth - 32);
      doc.text(lines, 22, y);
      y += lines.length * 4.5 + 3;

      if (y > pageHeight - 25) {
        doc.addPage();
        y = 20;
      }
    });
  }

  // ─── PAGE 2: CHARTS ─── //
  if (captureCharts) {
    doc.addPage();
    addHeader(doc, title, 'Visual Analytics');
    y = 50;

    // Expense chart
    const expenseChartImg = await captureElement('pdf-expense-chart');
    if (expenseChartImg) {
      y = addSectionTitle(doc, translations.expenseBreakdown || 'Expenses by Category', y);
      y += 5;
      try {
        const imgProps = doc.getImageProperties(expenseChartImg);
        const imgWidth = pageWidth - 28;
        const imgHeight = (imgProps.height * imgWidth) / imgProps.width;
        const finalHeight = Math.min(imgHeight, 80);
        const finalWidth = (imgProps.width * finalHeight) / imgProps.height;
        const xOffset = (pageWidth - finalWidth) / 2;
        doc.addImage(expenseChartImg, 'PNG', xOffset, y, finalWidth, finalHeight);
        y += finalHeight + 10;
      } catch (e) {
        console.error('Failed to add expense chart:', e);
      }
    }

    // Income chart
    if (y > pageHeight - 100) {
      doc.addPage();
      y = 20;
    }

    const incomeChartImg = await captureElement('pdf-income-chart');
    if (incomeChartImg) {
      y = addSectionTitle(doc, translations.incomeBreakdown || 'Income by Source', y);
      y += 5;
      try {
        const imgProps = doc.getImageProperties(incomeChartImg);
        const imgWidth = pageWidth - 28;
        const imgHeight = (imgProps.height * imgWidth) / imgProps.width;
        const finalHeight = Math.min(imgHeight, 80);
        const finalWidth = (imgProps.width * finalHeight) / imgProps.height;
        const xOffset = (pageWidth - finalWidth) / 2;
        doc.addImage(incomeChartImg, 'PNG', xOffset, y, finalWidth, finalHeight);
        y += finalHeight + 10;
      } catch (e) {
        console.error('Failed to add income chart:', e);
      }
    }

    // Trend chart
    if (y > pageHeight - 80) {
      doc.addPage();
      y = 20;
    }

    const trendChartImg = await captureElement('pdf-trend-chart');
    if (trendChartImg) {
      y = addSectionTitle(doc, translations.dailyTrend || 'Daily Trend', y);
      y += 5;
      try {
        const imgProps = doc.getImageProperties(trendChartImg);
        const imgWidth = pageWidth - 28;
        const imgHeight = (imgProps.height * imgWidth) / imgProps.width;
        const finalHeight = Math.min(imgHeight, 70);
        const finalWidth = (imgProps.width * finalHeight) / imgProps.height;
        const xOffset = (pageWidth - finalWidth) / 2;
        doc.addImage(trendChartImg, 'PNG', xOffset, y, finalWidth, finalHeight);
        y += finalHeight + 10;
      } catch (e) {
        console.error('Failed to add trend chart:', e);
      }
    }
  }

  // ─── PAGE 3: CATEGORY BREAKDOWN ─── //
  if (report.expensesByCategory?.length) {
    doc.addPage();
    addHeader(doc, title, 'Detailed Breakdown');
    y = 50;

    y = addSectionTitle(doc, translations.categoryBreakdown || 'Spending by Category', y);
    y += 5;

    // ✅ FIXED: autoTable(doc, options)
    autoTable(doc, {
      startY: y,
      head: [['Category', 'Amount', '%', 'Count']],
      body: report.expensesByCategory.map((c) => [
        c.category.charAt(0).toUpperCase() + c.category.slice(1),
        formatCurrency(c.amount),
        formatPercentage(c.percentage),
        String(c.count),
      ]),
      theme: 'striped',
      styles: { font: 'helvetica', fontSize: 9, cellPadding: 3 },
      headStyles: {
        fillColor: COLORS.primary,
        textColor: COLORS.white,
        fontStyle: 'bold',
      },
      alternateRowStyles: { fillColor: [248, 250, 247] },
      columnStyles: {
        1: { halign: 'right', fontStyle: 'bold' },
        2: { halign: 'right' },
        3: { halign: 'center' },
      },
    });

    y = doc.lastAutoTable.finalY + 12;

    // Income breakdown table
    if (report.incomeBySource?.length) {
      if (y > pageHeight - 60) {
        doc.addPage();
        y = 20;
      }

      y = addSectionTitle(doc, translations.incomeBreakdown || 'Income Sources', y);
      y += 5;

      autoTable(doc, {
        startY: y,
        head: [['Source', 'Amount', '%', 'Count']],
        body: report.incomeBySource.map((s) => [
          s.source,
          formatCurrency(s.amount),
          formatPercentage(s.percentage),
          String(s.count),
        ]),
        theme: 'striped',
        styles: { font: 'helvetica', fontSize: 9, cellPadding: 3 },
        headStyles: {
          fillColor: COLORS.primary,
          textColor: COLORS.white,
          fontStyle: 'bold',
        },
        alternateRowStyles: { fillColor: [248, 250, 247] },
        columnStyles: {
          1: { halign: 'right', fontStyle: 'bold' },
          2: { halign: 'right' },
          3: { halign: 'center' },
        },
      });
    }
  }

  // ─── SUGGESTIONS PAGE ─── //
  if (report.suggestions?.length) {
    doc.addPage();
    addHeader(doc, title, translations.suggestions || 'Smart Suggestions');
    y = 50;

    report.suggestions.forEach((s) => {
      if (y > pageHeight - 50) {
        doc.addPage();
        y = 20;
      }

      const cardHeight = 32;
      const colors = {
        success: [217, 236, 226],
        warning: [254, 215, 170],
        danger: [254, 202, 202],
        info: [191, 219, 254],
      };
      const textColors = {
        success: [21, 128, 61],
        warning: [194, 65, 12],
        danger: [185, 28, 28],
        info: [29, 78, 216],
      };

      doc.setFillColor(...(colors[s.type] || colors.info));
      doc.roundedRect(14, y, pageWidth - 28, cardHeight, 3, 3, 'F');

      doc.setTextColor(...(textColors[s.type] || textColors.info));
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(s.title, 18, y + 7);

      doc.setTextColor(...COLORS.text);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      const msgLines = doc.splitTextToSize(s.message, pageWidth - 36);
      doc.text(msgLines, 18, y + 14);

      if (s.tip) {
        doc.setFontSize(8);
        doc.setTextColor(...COLORS.textLight);
        doc.setFont('helvetica', 'italic');
        const tipLabel = translations.tip || 'Tip';
        const tipLines = doc.splitTextToSize(`${tipLabel}: ${s.tip}`, pageWidth - 36);
        doc.text(tipLines, 18, y + cardHeight - 4);
      }

      y += cardHeight + 5;
    });
  }

  // ─── ADD FOOTERS TO ALL PAGES ─── //
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages, footerText);
  }

  // ─── SAVE ─── //
  const fileName = `expenz-report-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
  return fileName;
};